[toolchain]
anchor_version = "0.28.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
billions_bounty = "4ZGXVxuYtaWE3Px4MRingBGSH1EhotBAsFFruhVQMvJK"
billions_bounty_v2 = "HDAfSw1n9o9iZynfEP54tnCf2KRa2cPVFnpTRFtM7Cfm"
billions_bounty_v3 = "52TDnXrrGRVGsTv6uE4a6cCs2YvELhe4hrtDt5dHoKov"

[programs.localnet]
billions_bounty = "4ZGXVxuYtaWE3Px4MRingBGSH1EhotBAsFFruhVQMvJK"
billions_bounty_v2 = "HDAfSw1n9o9iZynfEP54tnCf2KRa2cPVFnpTRFtM7Cfm"
billions_bounty_v3 = "52TDnXrrGRVGsTv6uE4a6cCs2YvELhe4hrtDt5dHoKov"

[programs.mainnet]
billions_bounty = "4ZGXVxuYtaWE3Px4MRingBGSH1EhotBAsFFruhVQMvJK"
billions_bounty_v2 = "HDAfSw1n9o9iZynfEP54tnCf2KRa2cPVFnpTRFtM7Cfm"
billions_bounty_v3 = "52TDnXrrGRVGsTv6uE4a6cCs2YvELhe4hrtDt5dHoKov"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false
