[features]
seeds = false
skip-lint = false

[programs.localnet]
billions_bounty_v3 = "7ZK2wtatnS8aqxCPt43pfLeUZGRqx5ucXXeZUngEboNh"

[programs.devnet]
billions_bounty_v3 = "7ZK2wtatnS8aqxCPt43pfLeUZGRqx5ucXXeZUngEboNh"

[programs.mainnet]
billions_bounty_v3 = "7ZK2wtatnS8aqxCPt43pfLeUZGRqx5ucXXeZUngEboNh"

[registry]
url = "https://api.apr.dev"

[toolchain]
anchor_version = "0.31.1"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha './tests/**/*.ts' --timeout 60000"

[test]
startup_wait = 5000

